/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 7.34.1
 * source: oamp/v1/knowledge.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export namespace oamp.v1 {
    export enum KnowledgeCategory {
        KNOWLEDGE_CATEGORY_UNSPECIFIED = 0,
        KNOWLEDGE_CATEGORY_FACT = 1,
        KNOWLEDGE_CATEGORY_PREFERENCE = 2,
        KNOWLEDGE_CATEGORY_PATTERN = 3,
        KNOWLEDGE_CATEGORY_CORRECTION = 4
    }
    export class KnowledgeSource extends pb_1.Message {
        #one_of_decls: number[][] = [[2]];
        constructor(data?: any[] | ({
            session_id?: string;
            timestamp?: string;
        } & (({
            agent_id?: string;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("session_id" in data && data.session_id != undefined) {
                    this.session_id = data.session_id;
                }
                if ("agent_id" in data && data.agent_id != undefined) {
                    this.agent_id = data.agent_id;
                }
                if ("timestamp" in data && data.timestamp != undefined) {
                    this.timestamp = data.timestamp;
                }
            }
        }
        get session_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set session_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get agent_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set agent_id(value: string) {
            pb_1.Message.setOneofField(this, 2, this.#one_of_decls[0], value);
        }
        get has_agent_id() {
            return pb_1.Message.getField(this, 2) != null;
        }
        get timestamp() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set timestamp(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get _agent_id() {
            const cases: {
                [index: number]: "none" | "agent_id";
            } = {
                0: "none",
                2: "agent_id"
            };
            return cases[pb_1.Message.computeOneofCase(this, [2])];
        }
        static fromObject(data: {
            session_id?: string;
            agent_id?: string;
            timestamp?: string;
        }): KnowledgeSource {
            const message = new KnowledgeSource({});
            if (data.session_id != null) {
                message.session_id = data.session_id;
            }
            if (data.agent_id != null) {
                message.agent_id = data.agent_id;
            }
            if (data.timestamp != null) {
                message.timestamp = data.timestamp;
            }
            return message;
        }
        toObject() {
            const data: {
                session_id?: string;
                agent_id?: string;
                timestamp?: string;
            } = {};
            if (this.session_id != null) {
                data.session_id = this.session_id;
            }
            if (this.agent_id != null) {
                data.agent_id = this.agent_id;
            }
            if (this.timestamp != null) {
                data.timestamp = this.timestamp;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.session_id.length)
                writer.writeString(1, this.session_id);
            if (this.has_agent_id)
                writer.writeString(2, this.agent_id);
            if (this.timestamp.length)
                writer.writeString(3, this.timestamp);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): KnowledgeSource {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new KnowledgeSource();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.session_id = reader.readString();
                        break;
                    case 2:
                        message.agent_id = reader.readString();
                        break;
                    case 3:
                        message.timestamp = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): KnowledgeSource {
            return KnowledgeSource.deserialize(bytes);
        }
    }
    export class KnowledgeDecay extends pb_1.Message {
        #one_of_decls: number[][] = [[1], [2]];
        constructor(data?: any[] | ({} & (({
            half_life_days?: number;
        }) | ({
            last_confirmed?: string;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("half_life_days" in data && data.half_life_days != undefined) {
                    this.half_life_days = data.half_life_days;
                }
                if ("last_confirmed" in data && data.last_confirmed != undefined) {
                    this.last_confirmed = data.last_confirmed;
                }
            }
        }
        get half_life_days() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set half_life_days(value: number) {
            pb_1.Message.setOneofField(this, 1, this.#one_of_decls[0], value);
        }
        get has_half_life_days() {
            return pb_1.Message.getField(this, 1) != null;
        }
        get last_confirmed() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set last_confirmed(value: string) {
            pb_1.Message.setOneofField(this, 2, this.#one_of_decls[1], value);
        }
        get has_last_confirmed() {
            return pb_1.Message.getField(this, 2) != null;
        }
        get _half_life_days() {
            const cases: {
                [index: number]: "none" | "half_life_days";
            } = {
                0: "none",
                1: "half_life_days"
            };
            return cases[pb_1.Message.computeOneofCase(this, [1])];
        }
        get _last_confirmed() {
            const cases: {
                [index: number]: "none" | "last_confirmed";
            } = {
                0: "none",
                2: "last_confirmed"
            };
            return cases[pb_1.Message.computeOneofCase(this, [2])];
        }
        static fromObject(data: {
            half_life_days?: number;
            last_confirmed?: string;
        }): KnowledgeDecay {
            const message = new KnowledgeDecay({});
            if (data.half_life_days != null) {
                message.half_life_days = data.half_life_days;
            }
            if (data.last_confirmed != null) {
                message.last_confirmed = data.last_confirmed;
            }
            return message;
        }
        toObject() {
            const data: {
                half_life_days?: number;
                last_confirmed?: string;
            } = {};
            if (this.half_life_days != null) {
                data.half_life_days = this.half_life_days;
            }
            if (this.last_confirmed != null) {
                data.last_confirmed = this.last_confirmed;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.has_half_life_days)
                writer.writeDouble(1, this.half_life_days);
            if (this.has_last_confirmed)
                writer.writeString(2, this.last_confirmed);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): KnowledgeDecay {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new KnowledgeDecay();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.half_life_days = reader.readDouble();
                        break;
                    case 2:
                        message.last_confirmed = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): KnowledgeDecay {
            return KnowledgeDecay.deserialize(bytes);
        }
    }
    export class KnowledgeEntry extends pb_1.Message {
        #one_of_decls: number[][] = [[9]];
        constructor(data?: any[] | ({
            oamp_version?: string;
            type?: string;
            id?: string;
            user_id?: string;
            category?: KnowledgeCategory;
            content?: string;
            confidence?: number;
            source?: KnowledgeSource;
            tags?: string[];
            metadata?: Map<string, string>;
        } & (({
            decay?: KnowledgeDecay;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [10], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("oamp_version" in data && data.oamp_version != undefined) {
                    this.oamp_version = data.oamp_version;
                }
                if ("type" in data && data.type != undefined) {
                    this.type = data.type;
                }
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("user_id" in data && data.user_id != undefined) {
                    this.user_id = data.user_id;
                }
                if ("category" in data && data.category != undefined) {
                    this.category = data.category;
                }
                if ("content" in data && data.content != undefined) {
                    this.content = data.content;
                }
                if ("confidence" in data && data.confidence != undefined) {
                    this.confidence = data.confidence;
                }
                if ("source" in data && data.source != undefined) {
                    this.source = data.source;
                }
                if ("decay" in data && data.decay != undefined) {
                    this.decay = data.decay;
                }
                if ("tags" in data && data.tags != undefined) {
                    this.tags = data.tags;
                }
                if ("metadata" in data && data.metadata != undefined) {
                    this.metadata = data.metadata;
                }
            }
            if (!this.metadata)
                this.metadata = new Map();
        }
        get oamp_version() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set oamp_version(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get type() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set type(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set id(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get user_id() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set user_id(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get category() {
            return pb_1.Message.getFieldWithDefault(this, 5, KnowledgeCategory.KNOWLEDGE_CATEGORY_UNSPECIFIED) as KnowledgeCategory;
        }
        set category(value: KnowledgeCategory) {
            pb_1.Message.setField(this, 5, value);
        }
        get content() {
            return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
        }
        set content(value: string) {
            pb_1.Message.setField(this, 6, value);
        }
        get confidence() {
            return pb_1.Message.getFieldWithDefault(this, 7, 0) as number;
        }
        set confidence(value: number) {
            pb_1.Message.setField(this, 7, value);
        }
        get source() {
            return pb_1.Message.getWrapperField(this, KnowledgeSource, 8) as KnowledgeSource;
        }
        set source(value: KnowledgeSource) {
            pb_1.Message.setWrapperField(this, 8, value);
        }
        get has_source() {
            return pb_1.Message.getField(this, 8) != null;
        }
        get decay() {
            return pb_1.Message.getWrapperField(this, KnowledgeDecay, 9) as KnowledgeDecay;
        }
        set decay(value: KnowledgeDecay) {
            pb_1.Message.setOneofWrapperField(this, 9, this.#one_of_decls[0], value);
        }
        get has_decay() {
            return pb_1.Message.getField(this, 9) != null;
        }
        get tags() {
            return pb_1.Message.getFieldWithDefault(this, 10, []) as string[];
        }
        set tags(value: string[]) {
            pb_1.Message.setField(this, 10, value);
        }
        get metadata() {
            return pb_1.Message.getField(this, 11) as any as Map<string, string>;
        }
        set metadata(value: Map<string, string>) {
            pb_1.Message.setField(this, 11, value as any);
        }
        get _decay() {
            const cases: {
                [index: number]: "none" | "decay";
            } = {
                0: "none",
                9: "decay"
            };
            return cases[pb_1.Message.computeOneofCase(this, [9])];
        }
        static fromObject(data: {
            oamp_version?: string;
            type?: string;
            id?: string;
            user_id?: string;
            category?: KnowledgeCategory;
            content?: string;
            confidence?: number;
            source?: ReturnType<typeof KnowledgeSource.prototype.toObject>;
            decay?: ReturnType<typeof KnowledgeDecay.prototype.toObject>;
            tags?: string[];
            metadata?: {
                [key: string]: string;
            };
        }): KnowledgeEntry {
            const message = new KnowledgeEntry({});
            if (data.oamp_version != null) {
                message.oamp_version = data.oamp_version;
            }
            if (data.type != null) {
                message.type = data.type;
            }
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.user_id != null) {
                message.user_id = data.user_id;
            }
            if (data.category != null) {
                message.category = data.category;
            }
            if (data.content != null) {
                message.content = data.content;
            }
            if (data.confidence != null) {
                message.confidence = data.confidence;
            }
            if (data.source != null) {
                message.source = KnowledgeSource.fromObject(data.source);
            }
            if (data.decay != null) {
                message.decay = KnowledgeDecay.fromObject(data.decay);
            }
            if (data.tags != null) {
                message.tags = data.tags;
            }
            if (typeof data.metadata == "object") {
                message.metadata = new Map(Object.entries(data.metadata));
            }
            return message;
        }
        toObject() {
            const data: {
                oamp_version?: string;
                type?: string;
                id?: string;
                user_id?: string;
                category?: KnowledgeCategory;
                content?: string;
                confidence?: number;
                source?: ReturnType<typeof KnowledgeSource.prototype.toObject>;
                decay?: ReturnType<typeof KnowledgeDecay.prototype.toObject>;
                tags?: string[];
                metadata?: {
                    [key: string]: string;
                };
            } = {};
            if (this.oamp_version != null) {
                data.oamp_version = this.oamp_version;
            }
            if (this.type != null) {
                data.type = this.type;
            }
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.user_id != null) {
                data.user_id = this.user_id;
            }
            if (this.category != null) {
                data.category = this.category;
            }
            if (this.content != null) {
                data.content = this.content;
            }
            if (this.confidence != null) {
                data.confidence = this.confidence;
            }
            if (this.source != null) {
                data.source = this.source.toObject();
            }
            if (this.decay != null) {
                data.decay = this.decay.toObject();
            }
            if (this.tags != null) {
                data.tags = this.tags;
            }
            if (this.metadata != null) {
                data.metadata = (Object.fromEntries)(this.metadata);
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.oamp_version.length)
                writer.writeString(1, this.oamp_version);
            if (this.type.length)
                writer.writeString(2, this.type);
            if (this.id.length)
                writer.writeString(3, this.id);
            if (this.user_id.length)
                writer.writeString(4, this.user_id);
            if (this.category != KnowledgeCategory.KNOWLEDGE_CATEGORY_UNSPECIFIED)
                writer.writeEnum(5, this.category);
            if (this.content.length)
                writer.writeString(6, this.content);
            if (this.confidence != 0)
                writer.writeFloat(7, this.confidence);
            if (this.has_source)
                writer.writeMessage(8, this.source, () => this.source.serialize(writer));
            if (this.has_decay)
                writer.writeMessage(9, this.decay, () => this.decay.serialize(writer));
            if (this.tags.length)
                writer.writeRepeatedString(10, this.tags);
            for (const [key, value] of this.metadata) {
                writer.writeMessage(11, this.metadata, () => {
                    writer.writeString(1, key);
                    writer.writeString(2, value);
                });
            }
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): KnowledgeEntry {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new KnowledgeEntry();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.oamp_version = reader.readString();
                        break;
                    case 2:
                        message.type = reader.readString();
                        break;
                    case 3:
                        message.id = reader.readString();
                        break;
                    case 4:
                        message.user_id = reader.readString();
                        break;
                    case 5:
                        message.category = reader.readEnum();
                        break;
                    case 6:
                        message.content = reader.readString();
                        break;
                    case 7:
                        message.confidence = reader.readFloat();
                        break;
                    case 8:
                        reader.readMessage(message.source, () => message.source = KnowledgeSource.deserialize(reader));
                        break;
                    case 9:
                        reader.readMessage(message.decay, () => message.decay = KnowledgeDecay.deserialize(reader));
                        break;
                    case 10:
                        pb_1.Message.addToRepeatedField(message, 10, reader.readString());
                        break;
                    case 11:
                        reader.readMessage(message, () => pb_1.Map.deserializeBinary(message.metadata as any, reader, reader.readString, reader.readString));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): KnowledgeEntry {
            return KnowledgeEntry.deserialize(bytes);
        }
    }
    export class KnowledgeStore extends pb_1.Message {
        #one_of_decls: number[][] = [[6]];
        constructor(data?: any[] | ({
            oamp_version?: string;
            type?: string;
            user_id?: string;
            entries?: KnowledgeEntry[];
            exported_at?: string;
        } & (({
            agent_id?: string;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [4], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("oamp_version" in data && data.oamp_version != undefined) {
                    this.oamp_version = data.oamp_version;
                }
                if ("type" in data && data.type != undefined) {
                    this.type = data.type;
                }
                if ("user_id" in data && data.user_id != undefined) {
                    this.user_id = data.user_id;
                }
                if ("entries" in data && data.entries != undefined) {
                    this.entries = data.entries;
                }
                if ("exported_at" in data && data.exported_at != undefined) {
                    this.exported_at = data.exported_at;
                }
                if ("agent_id" in data && data.agent_id != undefined) {
                    this.agent_id = data.agent_id;
                }
            }
        }
        get oamp_version() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set oamp_version(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get type() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set type(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get user_id() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set user_id(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get entries() {
            return pb_1.Message.getRepeatedWrapperField(this, KnowledgeEntry, 4) as KnowledgeEntry[];
        }
        set entries(value: KnowledgeEntry[]) {
            pb_1.Message.setRepeatedWrapperField(this, 4, value);
        }
        get exported_at() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set exported_at(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get agent_id() {
            return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
        }
        set agent_id(value: string) {
            pb_1.Message.setOneofField(this, 6, this.#one_of_decls[0], value);
        }
        get has_agent_id() {
            return pb_1.Message.getField(this, 6) != null;
        }
        get _agent_id() {
            const cases: {
                [index: number]: "none" | "agent_id";
            } = {
                0: "none",
                6: "agent_id"
            };
            return cases[pb_1.Message.computeOneofCase(this, [6])];
        }
        static fromObject(data: {
            oamp_version?: string;
            type?: string;
            user_id?: string;
            entries?: ReturnType<typeof KnowledgeEntry.prototype.toObject>[];
            exported_at?: string;
            agent_id?: string;
        }): KnowledgeStore {
            const message = new KnowledgeStore({});
            if (data.oamp_version != null) {
                message.oamp_version = data.oamp_version;
            }
            if (data.type != null) {
                message.type = data.type;
            }
            if (data.user_id != null) {
                message.user_id = data.user_id;
            }
            if (data.entries != null) {
                message.entries = data.entries.map(item => KnowledgeEntry.fromObject(item));
            }
            if (data.exported_at != null) {
                message.exported_at = data.exported_at;
            }
            if (data.agent_id != null) {
                message.agent_id = data.agent_id;
            }
            return message;
        }
        toObject() {
            const data: {
                oamp_version?: string;
                type?: string;
                user_id?: string;
                entries?: ReturnType<typeof KnowledgeEntry.prototype.toObject>[];
                exported_at?: string;
                agent_id?: string;
            } = {};
            if (this.oamp_version != null) {
                data.oamp_version = this.oamp_version;
            }
            if (this.type != null) {
                data.type = this.type;
            }
            if (this.user_id != null) {
                data.user_id = this.user_id;
            }
            if (this.entries != null) {
                data.entries = this.entries.map((item: KnowledgeEntry) => item.toObject());
            }
            if (this.exported_at != null) {
                data.exported_at = this.exported_at;
            }
            if (this.agent_id != null) {
                data.agent_id = this.agent_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.oamp_version.length)
                writer.writeString(1, this.oamp_version);
            if (this.type.length)
                writer.writeString(2, this.type);
            if (this.user_id.length)
                writer.writeString(3, this.user_id);
            if (this.entries.length)
                writer.writeRepeatedMessage(4, this.entries, (item: KnowledgeEntry) => item.serialize(writer));
            if (this.exported_at.length)
                writer.writeString(5, this.exported_at);
            if (this.has_agent_id)
                writer.writeString(6, this.agent_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): KnowledgeStore {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new KnowledgeStore();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.oamp_version = reader.readString();
                        break;
                    case 2:
                        message.type = reader.readString();
                        break;
                    case 3:
                        message.user_id = reader.readString();
                        break;
                    case 4:
                        reader.readMessage(message.entries, () => pb_1.Message.addToRepeatedWrapperField(message, 4, KnowledgeEntry.deserialize(reader), KnowledgeEntry));
                        break;
                    case 5:
                        message.exported_at = reader.readString();
                        break;
                    case 6:
                        message.agent_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): KnowledgeStore {
            return KnowledgeStore.deserialize(bytes);
        }
    }
}
