/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 7.34.1
 * source: oamp/v1/user_model.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export namespace oamp.v1 {
    export enum ExpertiseLevel {
        EXPERTISE_LEVEL_UNSPECIFIED = 0,
        EXPERTISE_LEVEL_NOVICE = 1,
        EXPERTISE_LEVEL_INTERMEDIATE = 2,
        EXPERTISE_LEVEL_ADVANCED = 3,
        EXPERTISE_LEVEL_EXPERT = 4
    }
    export class CommunicationProfile extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            verbosity?: number;
            formality?: number;
            prefers_examples?: boolean;
            prefers_explanations?: boolean;
            languages?: string[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [5], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("verbosity" in data && data.verbosity != undefined) {
                    this.verbosity = data.verbosity;
                }
                if ("formality" in data && data.formality != undefined) {
                    this.formality = data.formality;
                }
                if ("prefers_examples" in data && data.prefers_examples != undefined) {
                    this.prefers_examples = data.prefers_examples;
                }
                if ("prefers_explanations" in data && data.prefers_explanations != undefined) {
                    this.prefers_explanations = data.prefers_explanations;
                }
                if ("languages" in data && data.languages != undefined) {
                    this.languages = data.languages;
                }
            }
        }
        get verbosity() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set verbosity(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get formality() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set formality(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get prefers_examples() {
            return pb_1.Message.getFieldWithDefault(this, 3, false) as boolean;
        }
        set prefers_examples(value: boolean) {
            pb_1.Message.setField(this, 3, value);
        }
        get prefers_explanations() {
            return pb_1.Message.getFieldWithDefault(this, 4, false) as boolean;
        }
        set prefers_explanations(value: boolean) {
            pb_1.Message.setField(this, 4, value);
        }
        get languages() {
            return pb_1.Message.getFieldWithDefault(this, 5, []) as string[];
        }
        set languages(value: string[]) {
            pb_1.Message.setField(this, 5, value);
        }
        static fromObject(data: {
            verbosity?: number;
            formality?: number;
            prefers_examples?: boolean;
            prefers_explanations?: boolean;
            languages?: string[];
        }): CommunicationProfile {
            const message = new CommunicationProfile({});
            if (data.verbosity != null) {
                message.verbosity = data.verbosity;
            }
            if (data.formality != null) {
                message.formality = data.formality;
            }
            if (data.prefers_examples != null) {
                message.prefers_examples = data.prefers_examples;
            }
            if (data.prefers_explanations != null) {
                message.prefers_explanations = data.prefers_explanations;
            }
            if (data.languages != null) {
                message.languages = data.languages;
            }
            return message;
        }
        toObject() {
            const data: {
                verbosity?: number;
                formality?: number;
                prefers_examples?: boolean;
                prefers_explanations?: boolean;
                languages?: string[];
            } = {};
            if (this.verbosity != null) {
                data.verbosity = this.verbosity;
            }
            if (this.formality != null) {
                data.formality = this.formality;
            }
            if (this.prefers_examples != null) {
                data.prefers_examples = this.prefers_examples;
            }
            if (this.prefers_explanations != null) {
                data.prefers_explanations = this.prefers_explanations;
            }
            if (this.languages != null) {
                data.languages = this.languages;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.verbosity != 0)
                writer.writeFloat(1, this.verbosity);
            if (this.formality != 0)
                writer.writeFloat(2, this.formality);
            if (this.prefers_examples != false)
                writer.writeBool(3, this.prefers_examples);
            if (this.prefers_explanations != false)
                writer.writeBool(4, this.prefers_explanations);
            if (this.languages.length)
                writer.writeRepeatedString(5, this.languages);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CommunicationProfile {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new CommunicationProfile();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.verbosity = reader.readFloat();
                        break;
                    case 2:
                        message.formality = reader.readFloat();
                        break;
                    case 3:
                        message.prefers_examples = reader.readBool();
                        break;
                    case 4:
                        message.prefers_explanations = reader.readBool();
                        break;
                    case 5:
                        pb_1.Message.addToRepeatedField(message, 5, reader.readString());
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): CommunicationProfile {
            return CommunicationProfile.deserialize(bytes);
        }
    }
    export class ExpertiseDomain extends pb_1.Message {
        #one_of_decls: number[][] = [[5]];
        constructor(data?: any[] | ({
            domain?: string;
            level?: ExpertiseLevel;
            confidence?: number;
            evidence_sessions?: string[];
        } & (({
            last_observed?: string;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [4], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("domain" in data && data.domain != undefined) {
                    this.domain = data.domain;
                }
                if ("level" in data && data.level != undefined) {
                    this.level = data.level;
                }
                if ("confidence" in data && data.confidence != undefined) {
                    this.confidence = data.confidence;
                }
                if ("evidence_sessions" in data && data.evidence_sessions != undefined) {
                    this.evidence_sessions = data.evidence_sessions;
                }
                if ("last_observed" in data && data.last_observed != undefined) {
                    this.last_observed = data.last_observed;
                }
            }
        }
        get domain() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set domain(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get level() {
            return pb_1.Message.getFieldWithDefault(this, 2, ExpertiseLevel.EXPERTISE_LEVEL_UNSPECIFIED) as ExpertiseLevel;
        }
        set level(value: ExpertiseLevel) {
            pb_1.Message.setField(this, 2, value);
        }
        get confidence() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set confidence(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get evidence_sessions() {
            return pb_1.Message.getFieldWithDefault(this, 4, []) as string[];
        }
        set evidence_sessions(value: string[]) {
            pb_1.Message.setField(this, 4, value);
        }
        get last_observed() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set last_observed(value: string) {
            pb_1.Message.setOneofField(this, 5, this.#one_of_decls[0], value);
        }
        get has_last_observed() {
            return pb_1.Message.getField(this, 5) != null;
        }
        get _last_observed() {
            const cases: {
                [index: number]: "none" | "last_observed";
            } = {
                0: "none",
                5: "last_observed"
            };
            return cases[pb_1.Message.computeOneofCase(this, [5])];
        }
        static fromObject(data: {
            domain?: string;
            level?: ExpertiseLevel;
            confidence?: number;
            evidence_sessions?: string[];
            last_observed?: string;
        }): ExpertiseDomain {
            const message = new ExpertiseDomain({});
            if (data.domain != null) {
                message.domain = data.domain;
            }
            if (data.level != null) {
                message.level = data.level;
            }
            if (data.confidence != null) {
                message.confidence = data.confidence;
            }
            if (data.evidence_sessions != null) {
                message.evidence_sessions = data.evidence_sessions;
            }
            if (data.last_observed != null) {
                message.last_observed = data.last_observed;
            }
            return message;
        }
        toObject() {
            const data: {
                domain?: string;
                level?: ExpertiseLevel;
                confidence?: number;
                evidence_sessions?: string[];
                last_observed?: string;
            } = {};
            if (this.domain != null) {
                data.domain = this.domain;
            }
            if (this.level != null) {
                data.level = this.level;
            }
            if (this.confidence != null) {
                data.confidence = this.confidence;
            }
            if (this.evidence_sessions != null) {
                data.evidence_sessions = this.evidence_sessions;
            }
            if (this.last_observed != null) {
                data.last_observed = this.last_observed;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.domain.length)
                writer.writeString(1, this.domain);
            if (this.level != ExpertiseLevel.EXPERTISE_LEVEL_UNSPECIFIED)
                writer.writeEnum(2, this.level);
            if (this.confidence != 0)
                writer.writeFloat(3, this.confidence);
            if (this.evidence_sessions.length)
                writer.writeRepeatedString(4, this.evidence_sessions);
            if (this.has_last_observed)
                writer.writeString(5, this.last_observed);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ExpertiseDomain {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ExpertiseDomain();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.domain = reader.readString();
                        break;
                    case 2:
                        message.level = reader.readEnum();
                        break;
                    case 3:
                        message.confidence = reader.readFloat();
                        break;
                    case 4:
                        pb_1.Message.addToRepeatedField(message, 4, reader.readString());
                        break;
                    case 5:
                        message.last_observed = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ExpertiseDomain {
            return ExpertiseDomain.deserialize(bytes);
        }
    }
    export class Correction extends pb_1.Message {
        #one_of_decls: number[][] = [[3]];
        constructor(data?: any[] | ({
            what_agent_did?: string;
            what_user_wanted?: string;
            session_id?: string;
            timestamp?: string;
        } & (({
            context?: string;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("what_agent_did" in data && data.what_agent_did != undefined) {
                    this.what_agent_did = data.what_agent_did;
                }
                if ("what_user_wanted" in data && data.what_user_wanted != undefined) {
                    this.what_user_wanted = data.what_user_wanted;
                }
                if ("context" in data && data.context != undefined) {
                    this.context = data.context;
                }
                if ("session_id" in data && data.session_id != undefined) {
                    this.session_id = data.session_id;
                }
                if ("timestamp" in data && data.timestamp != undefined) {
                    this.timestamp = data.timestamp;
                }
            }
        }
        get what_agent_did() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set what_agent_did(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get what_user_wanted() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set what_user_wanted(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get context() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set context(value: string) {
            pb_1.Message.setOneofField(this, 3, this.#one_of_decls[0], value);
        }
        get has_context() {
            return pb_1.Message.getField(this, 3) != null;
        }
        get session_id() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set session_id(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get timestamp() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set timestamp(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get _context() {
            const cases: {
                [index: number]: "none" | "context";
            } = {
                0: "none",
                3: "context"
            };
            return cases[pb_1.Message.computeOneofCase(this, [3])];
        }
        static fromObject(data: {
            what_agent_did?: string;
            what_user_wanted?: string;
            context?: string;
            session_id?: string;
            timestamp?: string;
        }): Correction {
            const message = new Correction({});
            if (data.what_agent_did != null) {
                message.what_agent_did = data.what_agent_did;
            }
            if (data.what_user_wanted != null) {
                message.what_user_wanted = data.what_user_wanted;
            }
            if (data.context != null) {
                message.context = data.context;
            }
            if (data.session_id != null) {
                message.session_id = data.session_id;
            }
            if (data.timestamp != null) {
                message.timestamp = data.timestamp;
            }
            return message;
        }
        toObject() {
            const data: {
                what_agent_did?: string;
                what_user_wanted?: string;
                context?: string;
                session_id?: string;
                timestamp?: string;
            } = {};
            if (this.what_agent_did != null) {
                data.what_agent_did = this.what_agent_did;
            }
            if (this.what_user_wanted != null) {
                data.what_user_wanted = this.what_user_wanted;
            }
            if (this.context != null) {
                data.context = this.context;
            }
            if (this.session_id != null) {
                data.session_id = this.session_id;
            }
            if (this.timestamp != null) {
                data.timestamp = this.timestamp;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.what_agent_did.length)
                writer.writeString(1, this.what_agent_did);
            if (this.what_user_wanted.length)
                writer.writeString(2, this.what_user_wanted);
            if (this.has_context)
                writer.writeString(3, this.context);
            if (this.session_id.length)
                writer.writeString(4, this.session_id);
            if (this.timestamp.length)
                writer.writeString(5, this.timestamp);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Correction {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Correction();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.what_agent_did = reader.readString();
                        break;
                    case 2:
                        message.what_user_wanted = reader.readString();
                        break;
                    case 3:
                        message.context = reader.readString();
                        break;
                    case 4:
                        message.session_id = reader.readString();
                        break;
                    case 5:
                        message.timestamp = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Correction {
            return Correction.deserialize(bytes);
        }
    }
    export class StatedPreference extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            key?: string;
            value?: string;
            timestamp?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("key" in data && data.key != undefined) {
                    this.key = data.key;
                }
                if ("value" in data && data.value != undefined) {
                    this.value = data.value;
                }
                if ("timestamp" in data && data.timestamp != undefined) {
                    this.timestamp = data.timestamp;
                }
            }
        }
        get key() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set key(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get value() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set value(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get timestamp() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set timestamp(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            key?: string;
            value?: string;
            timestamp?: string;
        }): StatedPreference {
            const message = new StatedPreference({});
            if (data.key != null) {
                message.key = data.key;
            }
            if (data.value != null) {
                message.value = data.value;
            }
            if (data.timestamp != null) {
                message.timestamp = data.timestamp;
            }
            return message;
        }
        toObject() {
            const data: {
                key?: string;
                value?: string;
                timestamp?: string;
            } = {};
            if (this.key != null) {
                data.key = this.key;
            }
            if (this.value != null) {
                data.value = this.value;
            }
            if (this.timestamp != null) {
                data.timestamp = this.timestamp;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.key.length)
                writer.writeString(1, this.key);
            if (this.value.length)
                writer.writeString(2, this.value);
            if (this.timestamp.length)
                writer.writeString(3, this.timestamp);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): StatedPreference {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new StatedPreference();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.key = reader.readString();
                        break;
                    case 2:
                        message.value = reader.readString();
                        break;
                    case 3:
                        message.timestamp = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): StatedPreference {
            return StatedPreference.deserialize(bytes);
        }
    }
    export class UserModel extends pb_1.Message {
        #one_of_decls: number[][] = [[6]];
        constructor(data?: any[] | ({
            oamp_version?: string;
            type?: string;
            user_id?: string;
            model_version?: number;
            updated_at?: string;
            expertise?: ExpertiseDomain[];
            corrections?: Correction[];
            stated_preferences?: StatedPreference[];
            metadata?: Map<string, string>;
        } & (({
            communication?: CommunicationProfile;
        })))) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [7, 8, 9], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("oamp_version" in data && data.oamp_version != undefined) {
                    this.oamp_version = data.oamp_version;
                }
                if ("type" in data && data.type != undefined) {
                    this.type = data.type;
                }
                if ("user_id" in data && data.user_id != undefined) {
                    this.user_id = data.user_id;
                }
                if ("model_version" in data && data.model_version != undefined) {
                    this.model_version = data.model_version;
                }
                if ("updated_at" in data && data.updated_at != undefined) {
                    this.updated_at = data.updated_at;
                }
                if ("communication" in data && data.communication != undefined) {
                    this.communication = data.communication;
                }
                if ("expertise" in data && data.expertise != undefined) {
                    this.expertise = data.expertise;
                }
                if ("corrections" in data && data.corrections != undefined) {
                    this.corrections = data.corrections;
                }
                if ("stated_preferences" in data && data.stated_preferences != undefined) {
                    this.stated_preferences = data.stated_preferences;
                }
                if ("metadata" in data && data.metadata != undefined) {
                    this.metadata = data.metadata;
                }
            }
            if (!this.metadata)
                this.metadata = new Map();
        }
        get oamp_version() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set oamp_version(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get type() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set type(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get user_id() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set user_id(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get model_version() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set model_version(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get updated_at() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set updated_at(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get communication() {
            return pb_1.Message.getWrapperField(this, CommunicationProfile, 6) as CommunicationProfile;
        }
        set communication(value: CommunicationProfile) {
            pb_1.Message.setOneofWrapperField(this, 6, this.#one_of_decls[0], value);
        }
        get has_communication() {
            return pb_1.Message.getField(this, 6) != null;
        }
        get expertise() {
            return pb_1.Message.getRepeatedWrapperField(this, ExpertiseDomain, 7) as ExpertiseDomain[];
        }
        set expertise(value: ExpertiseDomain[]) {
            pb_1.Message.setRepeatedWrapperField(this, 7, value);
        }
        get corrections() {
            return pb_1.Message.getRepeatedWrapperField(this, Correction, 8) as Correction[];
        }
        set corrections(value: Correction[]) {
            pb_1.Message.setRepeatedWrapperField(this, 8, value);
        }
        get stated_preferences() {
            return pb_1.Message.getRepeatedWrapperField(this, StatedPreference, 9) as StatedPreference[];
        }
        set stated_preferences(value: StatedPreference[]) {
            pb_1.Message.setRepeatedWrapperField(this, 9, value);
        }
        get metadata() {
            return pb_1.Message.getField(this, 10) as any as Map<string, string>;
        }
        set metadata(value: Map<string, string>) {
            pb_1.Message.setField(this, 10, value as any);
        }
        get _communication() {
            const cases: {
                [index: number]: "none" | "communication";
            } = {
                0: "none",
                6: "communication"
            };
            return cases[pb_1.Message.computeOneofCase(this, [6])];
        }
        static fromObject(data: {
            oamp_version?: string;
            type?: string;
            user_id?: string;
            model_version?: number;
            updated_at?: string;
            communication?: ReturnType<typeof CommunicationProfile.prototype.toObject>;
            expertise?: ReturnType<typeof ExpertiseDomain.prototype.toObject>[];
            corrections?: ReturnType<typeof Correction.prototype.toObject>[];
            stated_preferences?: ReturnType<typeof StatedPreference.prototype.toObject>[];
            metadata?: {
                [key: string]: string;
            };
        }): UserModel {
            const message = new UserModel({});
            if (data.oamp_version != null) {
                message.oamp_version = data.oamp_version;
            }
            if (data.type != null) {
                message.type = data.type;
            }
            if (data.user_id != null) {
                message.user_id = data.user_id;
            }
            if (data.model_version != null) {
                message.model_version = data.model_version;
            }
            if (data.updated_at != null) {
                message.updated_at = data.updated_at;
            }
            if (data.communication != null) {
                message.communication = CommunicationProfile.fromObject(data.communication);
            }
            if (data.expertise != null) {
                message.expertise = data.expertise.map(item => ExpertiseDomain.fromObject(item));
            }
            if (data.corrections != null) {
                message.corrections = data.corrections.map(item => Correction.fromObject(item));
            }
            if (data.stated_preferences != null) {
                message.stated_preferences = data.stated_preferences.map(item => StatedPreference.fromObject(item));
            }
            if (typeof data.metadata == "object") {
                message.metadata = new Map(Object.entries(data.metadata));
            }
            return message;
        }
        toObject() {
            const data: {
                oamp_version?: string;
                type?: string;
                user_id?: string;
                model_version?: number;
                updated_at?: string;
                communication?: ReturnType<typeof CommunicationProfile.prototype.toObject>;
                expertise?: ReturnType<typeof ExpertiseDomain.prototype.toObject>[];
                corrections?: ReturnType<typeof Correction.prototype.toObject>[];
                stated_preferences?: ReturnType<typeof StatedPreference.prototype.toObject>[];
                metadata?: {
                    [key: string]: string;
                };
            } = {};
            if (this.oamp_version != null) {
                data.oamp_version = this.oamp_version;
            }
            if (this.type != null) {
                data.type = this.type;
            }
            if (this.user_id != null) {
                data.user_id = this.user_id;
            }
            if (this.model_version != null) {
                data.model_version = this.model_version;
            }
            if (this.updated_at != null) {
                data.updated_at = this.updated_at;
            }
            if (this.communication != null) {
                data.communication = this.communication.toObject();
            }
            if (this.expertise != null) {
                data.expertise = this.expertise.map((item: ExpertiseDomain) => item.toObject());
            }
            if (this.corrections != null) {
                data.corrections = this.corrections.map((item: Correction) => item.toObject());
            }
            if (this.stated_preferences != null) {
                data.stated_preferences = this.stated_preferences.map((item: StatedPreference) => item.toObject());
            }
            if (this.metadata != null) {
                data.metadata = (Object.fromEntries)(this.metadata);
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.oamp_version.length)
                writer.writeString(1, this.oamp_version);
            if (this.type.length)
                writer.writeString(2, this.type);
            if (this.user_id.length)
                writer.writeString(3, this.user_id);
            if (this.model_version != 0)
                writer.writeUint64(4, this.model_version);
            if (this.updated_at.length)
                writer.writeString(5, this.updated_at);
            if (this.has_communication)
                writer.writeMessage(6, this.communication, () => this.communication.serialize(writer));
            if (this.expertise.length)
                writer.writeRepeatedMessage(7, this.expertise, (item: ExpertiseDomain) => item.serialize(writer));
            if (this.corrections.length)
                writer.writeRepeatedMessage(8, this.corrections, (item: Correction) => item.serialize(writer));
            if (this.stated_preferences.length)
                writer.writeRepeatedMessage(9, this.stated_preferences, (item: StatedPreference) => item.serialize(writer));
            for (const [key, value] of this.metadata) {
                writer.writeMessage(10, this.metadata, () => {
                    writer.writeString(1, key);
                    writer.writeString(2, value);
                });
            }
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UserModel {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UserModel();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.oamp_version = reader.readString();
                        break;
                    case 2:
                        message.type = reader.readString();
                        break;
                    case 3:
                        message.user_id = reader.readString();
                        break;
                    case 4:
                        message.model_version = reader.readUint64();
                        break;
                    case 5:
                        message.updated_at = reader.readString();
                        break;
                    case 6:
                        reader.readMessage(message.communication, () => message.communication = CommunicationProfile.deserialize(reader));
                        break;
                    case 7:
                        reader.readMessage(message.expertise, () => pb_1.Message.addToRepeatedWrapperField(message, 7, ExpertiseDomain.deserialize(reader), ExpertiseDomain));
                        break;
                    case 8:
                        reader.readMessage(message.corrections, () => pb_1.Message.addToRepeatedWrapperField(message, 8, Correction.deserialize(reader), Correction));
                        break;
                    case 9:
                        reader.readMessage(message.stated_preferences, () => pb_1.Message.addToRepeatedWrapperField(message, 9, StatedPreference.deserialize(reader), StatedPreference));
                        break;
                    case 10:
                        reader.readMessage(message, () => pb_1.Map.deserializeBinary(message.metadata as any, reader, reader.readString, reader.readString));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): UserModel {
            return UserModel.deserialize(bytes);
        }
    }
}
