// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: oamp/v1/knowledge.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KnowledgeCategory int32

const (
	KnowledgeCategory_KNOWLEDGE_CATEGORY_UNSPECIFIED KnowledgeCategory = 0
	KnowledgeCategory_KNOWLEDGE_CATEGORY_FACT        KnowledgeCategory = 1
	KnowledgeCategory_KNOWLEDGE_CATEGORY_PREFERENCE  KnowledgeCategory = 2
	KnowledgeCategory_KNOWLEDGE_CATEGORY_PATTERN     KnowledgeCategory = 3
	KnowledgeCategory_KNOWLEDGE_CATEGORY_CORRECTION  KnowledgeCategory = 4
)

// Enum value maps for KnowledgeCategory.
var (
	KnowledgeCategory_name = map[int32]string{
		0: "KNOWLEDGE_CATEGORY_UNSPECIFIED",
		1: "KNOWLEDGE_CATEGORY_FACT",
		2: "KNOWLEDGE_CATEGORY_PREFERENCE",
		3: "KNOWLEDGE_CATEGORY_PATTERN",
		4: "KNOWLEDGE_CATEGORY_CORRECTION",
	}
	KnowledgeCategory_value = map[string]int32{
		"KNOWLEDGE_CATEGORY_UNSPECIFIED": 0,
		"KNOWLEDGE_CATEGORY_FACT":        1,
		"KNOWLEDGE_CATEGORY_PREFERENCE":  2,
		"KNOWLEDGE_CATEGORY_PATTERN":     3,
		"KNOWLEDGE_CATEGORY_CORRECTION":  4,
	}
)

func (x KnowledgeCategory) Enum() *KnowledgeCategory {
	p := new(KnowledgeCategory)
	*p = x
	return p
}

func (x KnowledgeCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KnowledgeCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_oamp_v1_knowledge_proto_enumTypes[0].Descriptor()
}

func (KnowledgeCategory) Type() protoreflect.EnumType {
	return &file_oamp_v1_knowledge_proto_enumTypes[0]
}

func (x KnowledgeCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KnowledgeCategory.Descriptor instead.
func (KnowledgeCategory) EnumDescriptor() ([]byte, []int) {
	return file_oamp_v1_knowledge_proto_rawDescGZIP(), []int{0}
}

type KnowledgeSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentId       *string                `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3,oneof" json:"agent_id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ISO 8601
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeSource) Reset() {
	*x = KnowledgeSource{}
	mi := &file_oamp_v1_knowledge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeSource) ProtoMessage() {}

func (x *KnowledgeSource) ProtoReflect() protoreflect.Message {
	mi := &file_oamp_v1_knowledge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeSource.ProtoReflect.Descriptor instead.
func (*KnowledgeSource) Descriptor() ([]byte, []int) {
	return file_oamp_v1_knowledge_proto_rawDescGZIP(), []int{0}
}

func (x *KnowledgeSource) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *KnowledgeSource) GetAgentId() string {
	if x != nil && x.AgentId != nil {
		return *x.AgentId
	}
	return ""
}

func (x *KnowledgeSource) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type KnowledgeDecay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HalfLifeDays  *float64               `protobuf:"fixed64,1,opt,name=half_life_days,json=halfLifeDays,proto3,oneof" json:"half_life_days,omitempty"`
	LastConfirmed *string                `protobuf:"bytes,2,opt,name=last_confirmed,json=lastConfirmed,proto3,oneof" json:"last_confirmed,omitempty"` // ISO 8601
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeDecay) Reset() {
	*x = KnowledgeDecay{}
	mi := &file_oamp_v1_knowledge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeDecay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeDecay) ProtoMessage() {}

func (x *KnowledgeDecay) ProtoReflect() protoreflect.Message {
	mi := &file_oamp_v1_knowledge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeDecay.ProtoReflect.Descriptor instead.
func (*KnowledgeDecay) Descriptor() ([]byte, []int) {
	return file_oamp_v1_knowledge_proto_rawDescGZIP(), []int{1}
}

func (x *KnowledgeDecay) GetHalfLifeDays() float64 {
	if x != nil && x.HalfLifeDays != nil {
		return *x.HalfLifeDays
	}
	return 0
}

func (x *KnowledgeDecay) GetLastConfirmed() string {
	if x != nil && x.LastConfirmed != nil {
		return *x.LastConfirmed
	}
	return ""
}

type KnowledgeEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OampVersion   string                 `protobuf:"bytes,1,opt,name=oamp_version,json=oampVersion,proto3" json:"oamp_version,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "knowledge_entry"
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Category      KnowledgeCategory      `protobuf:"varint,5,opt,name=category,proto3,enum=oamp.v1.KnowledgeCategory" json:"category,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Confidence    float32                `protobuf:"fixed32,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Source        *KnowledgeSource       `protobuf:"bytes,8,opt,name=source,proto3" json:"source,omitempty"`
	Decay         *KnowledgeDecay        `protobuf:"bytes,9,opt,name=decay,proto3,oneof" json:"decay,omitempty"`
	Tags          []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeEntry) Reset() {
	*x = KnowledgeEntry{}
	mi := &file_oamp_v1_knowledge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeEntry) ProtoMessage() {}

func (x *KnowledgeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_oamp_v1_knowledge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeEntry.ProtoReflect.Descriptor instead.
func (*KnowledgeEntry) Descriptor() ([]byte, []int) {
	return file_oamp_v1_knowledge_proto_rawDescGZIP(), []int{2}
}

func (x *KnowledgeEntry) GetOampVersion() string {
	if x != nil {
		return x.OampVersion
	}
	return ""
}

func (x *KnowledgeEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *KnowledgeEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KnowledgeEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *KnowledgeEntry) GetCategory() KnowledgeCategory {
	if x != nil {
		return x.Category
	}
	return KnowledgeCategory_KNOWLEDGE_CATEGORY_UNSPECIFIED
}

func (x *KnowledgeEntry) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *KnowledgeEntry) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *KnowledgeEntry) GetSource() *KnowledgeSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *KnowledgeEntry) GetDecay() *KnowledgeDecay {
	if x != nil {
		return x.Decay
	}
	return nil
}

func (x *KnowledgeEntry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *KnowledgeEntry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type KnowledgeStore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OampVersion   string                 `protobuf:"bytes,1,opt,name=oamp_version,json=oampVersion,proto3" json:"oamp_version,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "knowledge_store"
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Entries       []*KnowledgeEntry      `protobuf:"bytes,4,rep,name=entries,proto3" json:"entries,omitempty"`
	ExportedAt    string                 `protobuf:"bytes,5,opt,name=exported_at,json=exportedAt,proto3" json:"exported_at,omitempty"` // ISO 8601
	AgentId       *string                `protobuf:"bytes,6,opt,name=agent_id,json=agentId,proto3,oneof" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeStore) Reset() {
	*x = KnowledgeStore{}
	mi := &file_oamp_v1_knowledge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeStore) ProtoMessage() {}

func (x *KnowledgeStore) ProtoReflect() protoreflect.Message {
	mi := &file_oamp_v1_knowledge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeStore.ProtoReflect.Descriptor instead.
func (*KnowledgeStore) Descriptor() ([]byte, []int) {
	return file_oamp_v1_knowledge_proto_rawDescGZIP(), []int{3}
}

func (x *KnowledgeStore) GetOampVersion() string {
	if x != nil {
		return x.OampVersion
	}
	return ""
}

func (x *KnowledgeStore) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *KnowledgeStore) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *KnowledgeStore) GetEntries() []*KnowledgeEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *KnowledgeStore) GetExportedAt() string {
	if x != nil {
		return x.ExportedAt
	}
	return ""
}

func (x *KnowledgeStore) GetAgentId() string {
	if x != nil && x.AgentId != nil {
		return *x.AgentId
	}
	return ""
}

var File_oamp_v1_knowledge_proto protoreflect.FileDescriptor

const file_oamp_v1_knowledge_proto_rawDesc = "" +
	"\n" +
	"\x17oamp/v1/knowledge.proto\x12\aoamp.v1\"{\n" +
	"\x0fKnowledgeSource\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1e\n" +
	"\bagent_id\x18\x02 \x01(\tH\x00R\aagentId\x88\x01\x01\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestampB\v\n" +
	"\t_agent_id\"\x8d\x01\n" +
	"\x0eKnowledgeDecay\x12)\n" +
	"\x0ehalf_life_days\x18\x01 \x01(\x01H\x00R\fhalfLifeDays\x88\x01\x01\x12*\n" +
	"\x0elast_confirmed\x18\x02 \x01(\tH\x01R\rlastConfirmed\x88\x01\x01B\x11\n" +
	"\x0f_half_life_daysB\x11\n" +
	"\x0f_last_confirmed\"\xe6\x03\n" +
	"\x0eKnowledgeEntry\x12!\n" +
	"\foamp_version\x18\x01 \x01(\tR\voampVersion\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x126\n" +
	"\bcategory\x18\x05 \x01(\x0e2\x1a.oamp.v1.KnowledgeCategoryR\bcategory\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x02R\n" +
	"confidence\x120\n" +
	"\x06source\x18\b \x01(\v2\x18.oamp.v1.KnowledgeSourceR\x06source\x122\n" +
	"\x05decay\x18\t \x01(\v2\x17.oamp.v1.KnowledgeDecayH\x00R\x05decay\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12A\n" +
	"\bmetadata\x18\v \x03(\v2%.oamp.v1.KnowledgeEntry.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_decay\"\xe1\x01\n" +
	"\x0eKnowledgeStore\x12!\n" +
	"\foamp_version\x18\x01 \x01(\tR\voampVersion\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x121\n" +
	"\aentries\x18\x04 \x03(\v2\x17.oamp.v1.KnowledgeEntryR\aentries\x12\x1f\n" +
	"\vexported_at\x18\x05 \x01(\tR\n" +
	"exportedAt\x12\x1e\n" +
	"\bagent_id\x18\x06 \x01(\tH\x00R\aagentId\x88\x01\x01B\v\n" +
	"\t_agent_id*\xba\x01\n" +
	"\x11KnowledgeCategory\x12\"\n" +
	"\x1eKNOWLEDGE_CATEGORY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17KNOWLEDGE_CATEGORY_FACT\x10\x01\x12!\n" +
	"\x1dKNOWLEDGE_CATEGORY_PREFERENCE\x10\x02\x12\x1e\n" +
	"\x1aKNOWLEDGE_CATEGORY_PATTERN\x10\x03\x12!\n" +
	"\x1dKNOWLEDGE_CATEGORY_CORRECTION\x10\x04B4Z2github.com/deep-thinking-llc/oamp-go/proto/oamp/v1b\x06proto3"

var (
	file_oamp_v1_knowledge_proto_rawDescOnce sync.Once
	file_oamp_v1_knowledge_proto_rawDescData []byte
)

func file_oamp_v1_knowledge_proto_rawDescGZIP() []byte {
	file_oamp_v1_knowledge_proto_rawDescOnce.Do(func() {
		file_oamp_v1_knowledge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oamp_v1_knowledge_proto_rawDesc), len(file_oamp_v1_knowledge_proto_rawDesc)))
	})
	return file_oamp_v1_knowledge_proto_rawDescData
}

var file_oamp_v1_knowledge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_oamp_v1_knowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_oamp_v1_knowledge_proto_goTypes = []any{
	(KnowledgeCategory)(0),  // 0: oamp.v1.KnowledgeCategory
	(*KnowledgeSource)(nil), // 1: oamp.v1.KnowledgeSource
	(*KnowledgeDecay)(nil),  // 2: oamp.v1.KnowledgeDecay
	(*KnowledgeEntry)(nil),  // 3: oamp.v1.KnowledgeEntry
	(*KnowledgeStore)(nil),  // 4: oamp.v1.KnowledgeStore
	nil,                     // 5: oamp.v1.KnowledgeEntry.MetadataEntry
}
var file_oamp_v1_knowledge_proto_depIdxs = []int32{
	0, // 0: oamp.v1.KnowledgeEntry.category:type_name -> oamp.v1.KnowledgeCategory
	1, // 1: oamp.v1.KnowledgeEntry.source:type_name -> oamp.v1.KnowledgeSource
	2, // 2: oamp.v1.KnowledgeEntry.decay:type_name -> oamp.v1.KnowledgeDecay
	5, // 3: oamp.v1.KnowledgeEntry.metadata:type_name -> oamp.v1.KnowledgeEntry.MetadataEntry
	3, // 4: oamp.v1.KnowledgeStore.entries:type_name -> oamp.v1.KnowledgeEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_oamp_v1_knowledge_proto_init() }
func file_oamp_v1_knowledge_proto_init() {
	if File_oamp_v1_knowledge_proto != nil {
		return
	}
	file_oamp_v1_knowledge_proto_msgTypes[0].OneofWrappers = []any{}
	file_oamp_v1_knowledge_proto_msgTypes[1].OneofWrappers = []any{}
	file_oamp_v1_knowledge_proto_msgTypes[2].OneofWrappers = []any{}
	file_oamp_v1_knowledge_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oamp_v1_knowledge_proto_rawDesc), len(file_oamp_v1_knowledge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oamp_v1_knowledge_proto_goTypes,
		DependencyIndexes: file_oamp_v1_knowledge_proto_depIdxs,
		EnumInfos:         file_oamp_v1_knowledge_proto_enumTypes,
		MessageInfos:      file_oamp_v1_knowledge_proto_msgTypes,
	}.Build()
	File_oamp_v1_knowledge_proto = out.File
	file_oamp_v1_knowledge_proto_goTypes = nil
	file_oamp_v1_knowledge_proto_depIdxs = nil
}
