// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: oamp/v1/user_model.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExpertiseLevel int32

const (
	ExpertiseLevel_EXPERTISE_LEVEL_UNSPECIFIED  ExpertiseLevel = 0
	ExpertiseLevel_EXPERTISE_LEVEL_NOVICE       ExpertiseLevel = 1
	ExpertiseLevel_EXPERTISE_LEVEL_INTERMEDIATE ExpertiseLevel = 2
	ExpertiseLevel_EXPERTISE_LEVEL_ADVANCED     ExpertiseLevel = 3
	ExpertiseLevel_EXPERTISE_LEVEL_EXPERT       ExpertiseLevel = 4
)

// Enum value maps for ExpertiseLevel.
var (
	ExpertiseLevel_name = map[int32]string{
		0: "EXPERTISE_LEVEL_UNSPECIFIED",
		1: "EXPERTISE_LEVEL_NOVICE",
		2: "EXPERTISE_LEVEL_INTERMEDIATE",
		3: "EXPERTISE_LEVEL_ADVANCED",
		4: "EXPERTISE_LEVEL_EXPERT",
	}
	ExpertiseLevel_value = map[string]int32{
		"EXPERTISE_LEVEL_UNSPECIFIED":  0,
		"EXPERTISE_LEVEL_NOVICE":       1,
		"EXPERTISE_LEVEL_INTERMEDIATE": 2,
		"EXPERTISE_LEVEL_ADVANCED":     3,
		"EXPERTISE_LEVEL_EXPERT":       4,
	}
)

func (x ExpertiseLevel) Enum() *ExpertiseLevel {
	p := new(ExpertiseLevel)
	*p = x
	return p
}

func (x ExpertiseLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExpertiseLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_oamp_v1_user_model_proto_enumTypes[0].Descriptor()
}

func (ExpertiseLevel) Type() protoreflect.EnumType {
	return &file_oamp_v1_user_model_proto_enumTypes[0]
}

func (x ExpertiseLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExpertiseLevel.Descriptor instead.
func (ExpertiseLevel) EnumDescriptor() ([]byte, []int) {
	return file_oamp_v1_user_model_proto_rawDescGZIP(), []int{0}
}

type CommunicationProfile struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Verbosity           float32                `protobuf:"fixed32,1,opt,name=verbosity,proto3" json:"verbosity,omitempty"` // -1.0 to 1.0
	Formality           float32                `protobuf:"fixed32,2,opt,name=formality,proto3" json:"formality,omitempty"` // -1.0 to 1.0
	PrefersExamples     bool                   `protobuf:"varint,3,opt,name=prefers_examples,json=prefersExamples,proto3" json:"prefers_examples,omitempty"`
	PrefersExplanations bool                   `protobuf:"varint,4,opt,name=prefers_explanations,json=prefersExplanations,proto3" json:"prefers_explanations,omitempty"`
	Languages           []string               `protobuf:"bytes,5,rep,name=languages,proto3" json:"languages,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CommunicationProfile) Reset() {
	*x = CommunicationProfile{}
	mi := &file_oamp_v1_user_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunicationProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunicationProfile) ProtoMessage() {}

func (x *CommunicationProfile) ProtoReflect() protoreflect.Message {
	mi := &file_oamp_v1_user_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunicationProfile.ProtoReflect.Descriptor instead.
func (*CommunicationProfile) Descriptor() ([]byte, []int) {
	return file_oamp_v1_user_model_proto_rawDescGZIP(), []int{0}
}

func (x *CommunicationProfile) GetVerbosity() float32 {
	if x != nil {
		return x.Verbosity
	}
	return 0
}

func (x *CommunicationProfile) GetFormality() float32 {
	if x != nil {
		return x.Formality
	}
	return 0
}

func (x *CommunicationProfile) GetPrefersExamples() bool {
	if x != nil {
		return x.PrefersExamples
	}
	return false
}

func (x *CommunicationProfile) GetPrefersExplanations() bool {
	if x != nil {
		return x.PrefersExplanations
	}
	return false
}

func (x *CommunicationProfile) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

type ExpertiseDomain struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Domain           string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Level            ExpertiseLevel         `protobuf:"varint,2,opt,name=level,proto3,enum=oamp.v1.ExpertiseLevel" json:"level,omitempty"`
	Confidence       float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	EvidenceSessions []string               `protobuf:"bytes,4,rep,name=evidence_sessions,json=evidenceSessions,proto3" json:"evidence_sessions,omitempty"`
	LastObserved     *string                `protobuf:"bytes,5,opt,name=last_observed,json=lastObserved,proto3,oneof" json:"last_observed,omitempty"` // ISO 8601
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExpertiseDomain) Reset() {
	*x = ExpertiseDomain{}
	mi := &file_oamp_v1_user_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpertiseDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpertiseDomain) ProtoMessage() {}

func (x *ExpertiseDomain) ProtoReflect() protoreflect.Message {
	mi := &file_oamp_v1_user_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpertiseDomain.ProtoReflect.Descriptor instead.
func (*ExpertiseDomain) Descriptor() ([]byte, []int) {
	return file_oamp_v1_user_model_proto_rawDescGZIP(), []int{1}
}

func (x *ExpertiseDomain) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ExpertiseDomain) GetLevel() ExpertiseLevel {
	if x != nil {
		return x.Level
	}
	return ExpertiseLevel_EXPERTISE_LEVEL_UNSPECIFIED
}

func (x *ExpertiseDomain) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ExpertiseDomain) GetEvidenceSessions() []string {
	if x != nil {
		return x.EvidenceSessions
	}
	return nil
}

func (x *ExpertiseDomain) GetLastObserved() string {
	if x != nil && x.LastObserved != nil {
		return *x.LastObserved
	}
	return ""
}

type Correction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WhatAgentDid   string                 `protobuf:"bytes,1,opt,name=what_agent_did,json=whatAgentDid,proto3" json:"what_agent_did,omitempty"`
	WhatUserWanted string                 `protobuf:"bytes,2,opt,name=what_user_wanted,json=whatUserWanted,proto3" json:"what_user_wanted,omitempty"`
	Context        *string                `protobuf:"bytes,3,opt,name=context,proto3,oneof" json:"context,omitempty"`
	SessionId      string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Timestamp      string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ISO 8601
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Correction) Reset() {
	*x = Correction{}
	mi := &file_oamp_v1_user_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Correction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Correction) ProtoMessage() {}

func (x *Correction) ProtoReflect() protoreflect.Message {
	mi := &file_oamp_v1_user_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Correction.ProtoReflect.Descriptor instead.
func (*Correction) Descriptor() ([]byte, []int) {
	return file_oamp_v1_user_model_proto_rawDescGZIP(), []int{2}
}

func (x *Correction) GetWhatAgentDid() string {
	if x != nil {
		return x.WhatAgentDid
	}
	return ""
}

func (x *Correction) GetWhatUserWanted() string {
	if x != nil {
		return x.WhatUserWanted
	}
	return ""
}

func (x *Correction) GetContext() string {
	if x != nil && x.Context != nil {
		return *x.Context
	}
	return ""
}

func (x *Correction) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Correction) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type StatedPreference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ISO 8601
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatedPreference) Reset() {
	*x = StatedPreference{}
	mi := &file_oamp_v1_user_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatedPreference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatedPreference) ProtoMessage() {}

func (x *StatedPreference) ProtoReflect() protoreflect.Message {
	mi := &file_oamp_v1_user_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatedPreference.ProtoReflect.Descriptor instead.
func (*StatedPreference) Descriptor() ([]byte, []int) {
	return file_oamp_v1_user_model_proto_rawDescGZIP(), []int{3}
}

func (x *StatedPreference) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StatedPreference) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StatedPreference) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type UserModel struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OampVersion       string                 `protobuf:"bytes,1,opt,name=oamp_version,json=oampVersion,proto3" json:"oamp_version,omitempty"`
	Type              string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "user_model"
	UserId            string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ModelVersion      uint64                 `protobuf:"varint,4,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // ISO 8601
	Communication     *CommunicationProfile  `protobuf:"bytes,6,opt,name=communication,proto3,oneof" json:"communication,omitempty"`
	Expertise         []*ExpertiseDomain     `protobuf:"bytes,7,rep,name=expertise,proto3" json:"expertise,omitempty"`
	Corrections       []*Correction          `protobuf:"bytes,8,rep,name=corrections,proto3" json:"corrections,omitempty"`
	StatedPreferences []*StatedPreference    `protobuf:"bytes,9,rep,name=stated_preferences,json=statedPreferences,proto3" json:"stated_preferences,omitempty"`
	Metadata          map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserModel) Reset() {
	*x = UserModel{}
	mi := &file_oamp_v1_user_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserModel) ProtoMessage() {}

func (x *UserModel) ProtoReflect() protoreflect.Message {
	mi := &file_oamp_v1_user_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserModel.ProtoReflect.Descriptor instead.
func (*UserModel) Descriptor() ([]byte, []int) {
	return file_oamp_v1_user_model_proto_rawDescGZIP(), []int{4}
}

func (x *UserModel) GetOampVersion() string {
	if x != nil {
		return x.OampVersion
	}
	return ""
}

func (x *UserModel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UserModel) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserModel) GetModelVersion() uint64 {
	if x != nil {
		return x.ModelVersion
	}
	return 0
}

func (x *UserModel) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UserModel) GetCommunication() *CommunicationProfile {
	if x != nil {
		return x.Communication
	}
	return nil
}

func (x *UserModel) GetExpertise() []*ExpertiseDomain {
	if x != nil {
		return x.Expertise
	}
	return nil
}

func (x *UserModel) GetCorrections() []*Correction {
	if x != nil {
		return x.Corrections
	}
	return nil
}

func (x *UserModel) GetStatedPreferences() []*StatedPreference {
	if x != nil {
		return x.StatedPreferences
	}
	return nil
}

func (x *UserModel) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_oamp_v1_user_model_proto protoreflect.FileDescriptor

const file_oamp_v1_user_model_proto_rawDesc = "" +
	"\n" +
	"\x18oamp/v1/user_model.proto\x12\aoamp.v1\"\xce\x01\n" +
	"\x14CommunicationProfile\x12\x1c\n" +
	"\tverbosity\x18\x01 \x01(\x02R\tverbosity\x12\x1c\n" +
	"\tformality\x18\x02 \x01(\x02R\tformality\x12)\n" +
	"\x10prefers_examples\x18\x03 \x01(\bR\x0fprefersExamples\x121\n" +
	"\x14prefers_explanations\x18\x04 \x01(\bR\x13prefersExplanations\x12\x1c\n" +
	"\tlanguages\x18\x05 \x03(\tR\tlanguages\"\xe1\x01\n" +
	"\x0fExpertiseDomain\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12-\n" +
	"\x05level\x18\x02 \x01(\x0e2\x17.oamp.v1.ExpertiseLevelR\x05level\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12+\n" +
	"\x11evidence_sessions\x18\x04 \x03(\tR\x10evidenceSessions\x12(\n" +
	"\rlast_observed\x18\x05 \x01(\tH\x00R\flastObserved\x88\x01\x01B\x10\n" +
	"\x0e_last_observed\"\xc4\x01\n" +
	"\n" +
	"Correction\x12$\n" +
	"\x0ewhat_agent_did\x18\x01 \x01(\tR\fwhatAgentDid\x12(\n" +
	"\x10what_user_wanted\x18\x02 \x01(\tR\x0ewhatUserWanted\x12\x1d\n" +
	"\acontext\x18\x03 \x01(\tH\x00R\acontext\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestampB\n" +
	"\n" +
	"\b_context\"X\n" +
	"\x10StatedPreference\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"\xaf\x04\n" +
	"\tUserModel\x12!\n" +
	"\foamp_version\x18\x01 \x01(\tR\voampVersion\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12#\n" +
	"\rmodel_version\x18\x04 \x01(\x04R\fmodelVersion\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x12H\n" +
	"\rcommunication\x18\x06 \x01(\v2\x1d.oamp.v1.CommunicationProfileH\x00R\rcommunication\x88\x01\x01\x126\n" +
	"\texpertise\x18\a \x03(\v2\x18.oamp.v1.ExpertiseDomainR\texpertise\x125\n" +
	"\vcorrections\x18\b \x03(\v2\x13.oamp.v1.CorrectionR\vcorrections\x12H\n" +
	"\x12stated_preferences\x18\t \x03(\v2\x19.oamp.v1.StatedPreferenceR\x11statedPreferences\x12<\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2 .oamp.v1.UserModel.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x10\n" +
	"\x0e_communication*\xa9\x01\n" +
	"\x0eExpertiseLevel\x12\x1f\n" +
	"\x1bEXPERTISE_LEVEL_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16EXPERTISE_LEVEL_NOVICE\x10\x01\x12 \n" +
	"\x1cEXPERTISE_LEVEL_INTERMEDIATE\x10\x02\x12\x1c\n" +
	"\x18EXPERTISE_LEVEL_ADVANCED\x10\x03\x12\x1a\n" +
	"\x16EXPERTISE_LEVEL_EXPERT\x10\x04B4Z2github.com/deep-thinking-llc/oamp-go/proto/oamp/v1b\x06proto3"

var (
	file_oamp_v1_user_model_proto_rawDescOnce sync.Once
	file_oamp_v1_user_model_proto_rawDescData []byte
)

func file_oamp_v1_user_model_proto_rawDescGZIP() []byte {
	file_oamp_v1_user_model_proto_rawDescOnce.Do(func() {
		file_oamp_v1_user_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oamp_v1_user_model_proto_rawDesc), len(file_oamp_v1_user_model_proto_rawDesc)))
	})
	return file_oamp_v1_user_model_proto_rawDescData
}

var file_oamp_v1_user_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_oamp_v1_user_model_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_oamp_v1_user_model_proto_goTypes = []any{
	(ExpertiseLevel)(0),          // 0: oamp.v1.ExpertiseLevel
	(*CommunicationProfile)(nil), // 1: oamp.v1.CommunicationProfile
	(*ExpertiseDomain)(nil),      // 2: oamp.v1.ExpertiseDomain
	(*Correction)(nil),           // 3: oamp.v1.Correction
	(*StatedPreference)(nil),     // 4: oamp.v1.StatedPreference
	(*UserModel)(nil),            // 5: oamp.v1.UserModel
	nil,                          // 6: oamp.v1.UserModel.MetadataEntry
}
var file_oamp_v1_user_model_proto_depIdxs = []int32{
	0, // 0: oamp.v1.ExpertiseDomain.level:type_name -> oamp.v1.ExpertiseLevel
	1, // 1: oamp.v1.UserModel.communication:type_name -> oamp.v1.CommunicationProfile
	2, // 2: oamp.v1.UserModel.expertise:type_name -> oamp.v1.ExpertiseDomain
	3, // 3: oamp.v1.UserModel.corrections:type_name -> oamp.v1.Correction
	4, // 4: oamp.v1.UserModel.stated_preferences:type_name -> oamp.v1.StatedPreference
	6, // 5: oamp.v1.UserModel.metadata:type_name -> oamp.v1.UserModel.MetadataEntry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_oamp_v1_user_model_proto_init() }
func file_oamp_v1_user_model_proto_init() {
	if File_oamp_v1_user_model_proto != nil {
		return
	}
	file_oamp_v1_user_model_proto_msgTypes[1].OneofWrappers = []any{}
	file_oamp_v1_user_model_proto_msgTypes[2].OneofWrappers = []any{}
	file_oamp_v1_user_model_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oamp_v1_user_model_proto_rawDesc), len(file_oamp_v1_user_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oamp_v1_user_model_proto_goTypes,
		DependencyIndexes: file_oamp_v1_user_model_proto_depIdxs,
		EnumInfos:         file_oamp_v1_user_model_proto_enumTypes,
		MessageInfos:      file_oamp_v1_user_model_proto_msgTypes,
	}.Build()
	File_oamp_v1_user_model_proto = out.File
	file_oamp_v1_user_model_proto_goTypes = nil
	file_oamp_v1_user_model_proto_depIdxs = nil
}
