# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oamp/v1/knowledge.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oamp/v1/knowledge.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17oamp/v1/knowledge.proto\x12\x07oamp.v1\"\\\n\x0fKnowledgeSource\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x15\n\x08\x61gent_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x11\n\ttimestamp\x18\x03 \x01(\tB\x0b\n\t_agent_id\"p\n\x0eKnowledgeDecay\x12\x1b\n\x0ehalf_life_days\x18\x01 \x01(\x01H\x00\x88\x01\x01\x12\x1b\n\x0elast_confirmed\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x11\n\x0f_half_life_daysB\x11\n\x0f_last_confirmed\"\xfd\x02\n\x0eKnowledgeEntry\x12\x14\n\x0coamp_version\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\x12,\n\x08\x63\x61tegory\x18\x05 \x01(\x0e\x32\x1a.oamp.v1.KnowledgeCategory\x12\x0f\n\x07\x63ontent\x18\x06 \x01(\t\x12\x12\n\nconfidence\x18\x07 \x01(\x02\x12(\n\x06source\x18\x08 \x01(\x0b\x32\x18.oamp.v1.KnowledgeSource\x12+\n\x05\x64\x65\x63\x61y\x18\t \x01(\x0b\x32\x17.oamp.v1.KnowledgeDecayH\x00\x88\x01\x01\x12\x0c\n\x04tags\x18\n \x03(\t\x12\x37\n\x08metadata\x18\x0b \x03(\x0b\x32%.oamp.v1.KnowledgeEntry.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x08\n\x06_decay\"\xa8\x01\n\x0eKnowledgeStore\x12\x14\n\x0coamp_version\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12(\n\x07\x65ntries\x18\x04 \x03(\x0b\x32\x17.oamp.v1.KnowledgeEntry\x12\x13\n\x0b\x65xported_at\x18\x05 \x01(\t\x12\x15\n\x08\x61gent_id\x18\x06 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_agent_id*\xba\x01\n\x11KnowledgeCategory\x12\"\n\x1eKNOWLEDGE_CATEGORY_UNSPECIFIED\x10\x00\x12\x1b\n\x17KNOWLEDGE_CATEGORY_FACT\x10\x01\x12!\n\x1dKNOWLEDGE_CATEGORY_PREFERENCE\x10\x02\x12\x1e\n\x1aKNOWLEDGE_CATEGORY_PATTERN\x10\x03\x12!\n\x1dKNOWLEDGE_CATEGORY_CORRECTION\x10\x04\x42\x34Z2github.com/deep-thinking-llc/oamp-go/proto/oamp/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oamp.v1.knowledge_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/deep-thinking-llc/oamp-go/proto/oamp/v1'
  _globals['_KNOWLEDGEENTRY_METADATAENTRY']._loaded_options = None
  _globals['_KNOWLEDGEENTRY_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_KNOWLEDGECATEGORY']._serialized_start=800
  _globals['_KNOWLEDGECATEGORY']._serialized_end=986
  _globals['_KNOWLEDGESOURCE']._serialized_start=36
  _globals['_KNOWLEDGESOURCE']._serialized_end=128
  _globals['_KNOWLEDGEDECAY']._serialized_start=130
  _globals['_KNOWLEDGEDECAY']._serialized_end=242
  _globals['_KNOWLEDGEENTRY']._serialized_start=245
  _globals['_KNOWLEDGEENTRY']._serialized_end=626
  _globals['_KNOWLEDGEENTRY_METADATAENTRY']._serialized_start=569
  _globals['_KNOWLEDGEENTRY_METADATAENTRY']._serialized_end=616
  _globals['_KNOWLEDGESTORE']._serialized_start=629
  _globals['_KNOWLEDGESTORE']._serialized_end=797
# @@protoc_insertion_point(module_scope)
